---
title: "Two Proportions by Bayes"
author: 
  - Denise Welsch
  - Contributors^[Students Names]
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  pdf_document:
    latex_engine: xelatex
    toc: true
    toc_depth: 2
#bibliography: ["references.bib"]
classoption: landscape
params:
  data: NA
  filename: NA
  fencoding: NA # used in Shiny app 
  decimal: NA
  enc_guessed: NA # used in Shiny app 
  level: NA
  outcome: NA
  exposure: NA 
  s1: NA 
  n1: NA 
  s2: NA 
  n2: NA
  a1: NA
  b1: NA
  a2: NA
  b2: NA
  user_selection_function_param: NA
  rope_user: NA
header-includes:
   - \usepackage{xcolor}
#   - \setmainfont[BoldFont=FiraSans-Bold, Extension=.otf]{FiraSans-Regular}  # used in Shiny app 
   - \usepackage{booktabs}
   - \usepackage{longtable}
   - \usepackage{float}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, comment='', message = FALSE, error = TRUE, warning=FALSE, fig.width=8)

# Import libraries used further below
library(knitr) # for tables
library(kableExtra) # for tables 
library(plotly) # for 3d plots
library(bayestestR)
library(LearnBayes)
```


```{r chunksinit}
# Initialize evaluation resp. execution of subsequent chunks
## Evaluation only for file upload, 
evalfile <- is.data.frame(params$data)
## Evaluation for cell frequency upload 
eval <- !is.na(params$s1)
## Other 
evalbasic_file <- FALSE
eval_rows <- FALSE
```


```{r getdatafile, eval = evalfile}
# Get data as a file 
tryCatch({
  
  # Get data
  df <- params$data
  
  # Save a copy for other purposes (downloadable code) 
  df_code <- df
  
  # Restrict to exposure and outcome
  vars <- c(params$outcome, params$exposure)
  df <- df[,vars,drop=FALSE]
  
  # Drop empty rows
  rowsums <- data.frame(sapply(df,is.na))
  if (length(which(rowSums(rowsums) == dim(df)[2])) != 0L){
    eval_rows <- TRUE
    rows_drop <- (which(rowSums(rowsums) == dim(df)[2]))
    length_non_complete <- length(which(rowSums(rowsums) == dim(df)[2]))
    df <- df[-rows_drop, ,drop=FALSE]
  }
  
  # Initialize next computations
  eval <- TRUE
  
  # Move on if file upload and successful current chunk 
  evalbasic_file <- as.logical(evalfile*eval)

}, error=function(e) {
  
  stop(safeError("Could not get the file data. "))
})



```

```{r freqfromfile, results="asis", eval=evalbasic_file}
# Compute cell frequencies from dataframe 
# Use s1,n1,s2,n2 for the names of the cell freq 
```

\pagebreak

```{r guititle, results="asis", eval=eval}
cat("# User Selection", fill=TRUE)
```

```{r guifile, results="asis", eval=evalbasic_file}
# Basic information for the case file upload
cat("Automatic statistics for the file:", fill=TRUE)
dataname <- params$filename[1]
kable(dataname, col.names = "File", linesep = '', longtable=T) 

cat("Your selection for the encoding:", fill=TRUE)
if (params$fencoding=="unknown"){
  cat("Auto")
} else {cat("UTF-8")}
cat("\\newline",fill=TRUE) 

cat("Your selection for the decimal character:", fill=TRUE)
if (params$decimal=="auto"){
  cat("Auto")
} else {cat(params$decimal)}
cat("\\newline",fill=TRUE) 
  
cat("Observations (rows with at least one non-missing value): ", fill=TRUE)
cat(dim(df)[1])
cat("\\newline",fill=TRUE) 

# Missing rows
if (exists("length_non_complete")){
  cat("Number of rows that are dropped because they contain no values (all values are missing):", length_non_complete)
  cat("\\newline",fill=TRUE) 
}

if (exists("vars")){
  cat("Name of the Outcome Variable: ", params$outcome, fill=TRUE)
  cat("\\newline",fill=TRUE) 
}

if (exists("vars")){
  cat("Name of the Exposure Variable: ", params$exposure, fill=TRUE)
}
```


```{r cellupload, eval=!evalfile, results='asis'}
# Upload as cell frequencies, display them nicely
cat(s1,fill=TRUE)
cat(n1,fill=TRUE)
cat(s2,fill=TRUE)
cat(n2,fill=TRUE)
```


```{r guirest, eval=eval, results='asis'}
# display in the report the rest of the information arising from the GUI (e.g. priors, function of parameters etc.)
```

\pagebreak

```{r preamble, eval=eval, results='asis'}
cat("# Goals of the Analysis", fill=TRUE)
# Why Bayesian. Explain what benefits will be gleaned by a Bayesian analysis (as opposed to a frequentist analysis).
# Goals of analysis. Explain the goals of the analysis. This prepares the audience for the type of models to expect and how the results will be described. 
# Check references: Kruschke, John K., Bayesian Analysis Reporting Guidelines, Nature Human Behaviour, 2021
```

```{r title_descstats, eval=eval, results='asis'}
cat("# The Data", fill=TRUE)
```

```{r datahead, eval=evalbasic_file, results='asis'}
cat("## Data Head (first five observations)", fill=TRUE)
knitr::kable(head(df), col.names = c("Outcome", "Exposure"), linesep = '', longtable=T) %>%
  kable_styling(font_size = 8, position = "center", full_width = FALSE, latex_options = c("HOLD_position","repeat_header"))
```

```{r desctable, eval=eval, dev="cairo_pdf", results='asis'}
cat("## Frequency Table", fill=TRUE)
# Insert a nice frequency and percentage table for the data
```

```{r descplots, eval=eval, dev="cairo_pdf", results='asis'}
cat("## Barplots", fill=TRUE)
# Insert beautiful descriptive plots suitable for our data, e.g. barplots and if you want to also other kind 
```

```{r the_model, eval=eval, results='asis'}
cat("# The Model", fill=TRUE)
cat("\n## Notation", fill=TRUE)
# Insert latex equations for the model 
# Highlight and explain the parameters in natural language
# Display and explain the user selected funtion of parameters 
```

```{r likelihood, eval=eval, results='asis'}
cat("## The Likelihood", fill=TRUE)

# Insert equation as latex or as code

# Plot the likelihood (follow second row from page 167 DDBA)
## Region to plot 
Theta1 = seq(0.001, 0.999, by=0.001) 
Theta2 = seq(0.001, 0.999, by=0.001) 

## Check the next line as a solution, export as a png and include or find another solution 
## plot_ly(x = Theta1, y = Theta2, z = ..., type = "surface") 
```

```{r priortext, eval=eval, results='asis'}
cat("## The Prior Distribution", fill=TRUE)
# if the default is used, explain and justify the prior distribution of the parameters in the model.
# otherwise, display again the user defined priors 
```

```{r priorplot, eval=eval, results='asis'}
# Plot the prior (follow first row from page 167 DDBA)
pTheta1 = dbeta(Theta1,a1,b1)
pTheta2 = dbeta(Theta2,a2,b2) 

## Check the next line as a solution, export as a png and include or find another solution 
## plot_ly(x = Theta1, y = Theta2, z = ..., type = "surface") 
```

```{r priorcheck, eval=eval, results='asis'}
cat("### Prior Predictive Check", fill=TRUE)
# Prior predictive check. Especially when using informed priors but even with broad priors, it is valuable to report a prior predictive check to demonstrate that the prior really generates simulated data consistent with the assumed prior knowledge.
# References: Jim Albert page 31, plots similar to BARG-Supplement 6.1.2
```


```{r posterior, eval=eval, dev="cairo_pdf", results='asis'}
cat("## The Posterior Distribution", fill=TRUE)
# Insert latex or code equation for the posterior distribution 

# Posterior for plotting (follow last row from page 167 DDBA)
pTheta1Theta2GivenData <- matrix(data=NA, nrow=length(Theta1), ncol=length(Theta2))
for (i in 1:length(Theta1)){
  for (j in 1:length(Theta2)){
    pTheta1Theta2GivenData[i,j]<- dbeta(Theta1[i], a1+s1, b1+n1-s1)*dbeta(Theta2[j], a2+s2, b2+n2-s2)   
  }
} 

## Generate plot, export as a png and include or find another solution 
## plot_ly(x = Theta1, y = Theta2, z = pTheta1Theta2GivenData, type = "surface") 
```

```{r posterior_check, eval=eval, dev="cairo_pdf", results='asis'}
cat("### Posterior Predictive Check", fill=TRUE)
# Posterior predictive check. Provide a posterior predictive check to show that the model usefully mimics the data.
# References: Jim Albert page 31, plots similar to BARG-Supplement 6.1.2
```

```{r simulate, eval=eval}
## Simulate from posterior
posterior_Theta1 <- rbeta(10000,s1+a1,(n1-s1)+b1)
posterior_Theta2 <- rbeta(10000,s2+a2,(n2-s2)+b2)
```

```{r functionparameter, eval=eval}
## Function of parameters of interest
if (user_selection_function_param == 3) {
  estimate <- 1-posterior_Theta1/posterior_Theta2
} else if (user_selection_function_param == 2){
  estimate <- posterior_Theta1/posterior_Theta2  
} else {
  estimate <- posterior_Theta1-posterior_Theta2  
}
```

```{r function_posterior, eval=eval, results="asis"}
cat("# Primary Interest", fill=TRUE)
cat("\n## Summary", fill=TRUE)
```


```{r function_posterior2, eval=eval}
# Summarize posterior in a table. For continuous parameters, derived functions of parameters and predicted values, report the central tendency and limits of the credible interval. Explicitly state whether you are using density-based values (mode and HDI) or quantile-based values (median and ETI), and state the mass of the credible interval (for example, 95%)
if (is.null(rope_user)==TRUE){
  describe_posterior(estimate, ci = 0.95, centrality="all", dispersion=TRUE, test=NULL)
} else {
  describe_posterior(estimate, ci = 0.95, centrality="all", dispersion=TRUE, test="rope", rope_range = rope_user)
  # ROPE limits and decisions. 
}
```


```{r plot_hdi, eval=eval, dev="cairo_pdf", results="asis"}
cat("## HDI Plot", fill=TRUE)
# Display graphical posterior information
# Use bayestestR package 
plot(hdi(estimate, ci = c(.89, .95, .99)))
```

```{r plot_eti, eval=eval, dev="cairo_pdf", results="asis"}
cat("## ETI Plot", fill=TRUE)
## Display graphical posterior information
### Use bayestestR package 
plot(eti(estimate))
```

```{r plotpost, eval=rope_user, dev="cairo_pdf", results="asis"}
cat("## More Plots", fill=TRUE)
# Use the plotPost function (page 205 Kruschke)
```

```{r}
# Clean environment 
rm(list=ls())
```